spring:
  application:
    name: dto

  profiles:
    active:
    - test

  # Data Source configuration
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: sa
    password: 

  # JPA configuration
  jpa:
    hibernate:
      # Options: 
      #ddl-auto: validate
      #ddl-auto: create-only
      #ddl-auto: drop
      #ddl-auto: update
      #ddl-auto: create-drop
      ddl-auto: none
      #ddl-auto: create
    #defer-datasource-initialization: true
    show-sql: false
    open-in-view: false

  h2:
    console:
      enabled: true
      path: /h2-console

# Logging configuration
logging:
  level:
    # TRACE, DEBUG, INFO, WARN, ERROR
    root: warn
    '[br.com.tiagomendonca.logging]': debug
